# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
cache: bundler

before_install:
    - gem update cocoapods

before_script:
    - export LANG=en_US.UTF-8
    - make ci

script:
    - make test
